---
# tasks file for deploy_nginx
- name: NGINX | Install EPEL Repo package from standart repo
  yum:
    name: epel-release
    state: present
  tags: 
    - epel-package
    - packages
      
- name: NGINX | install NGINX package from EPEL repo
  yum: 
    name: nginx
    state: latest
  notify: 
    - restart nginx
  tags:
    - nginx-package
    - pakages  

- name: NGINX | Create NGINX config file from template
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - reload nginx
  tags:
    - nginx-configuration

- name: NGINX | Make another start page
  copy:
    src: index.html
    dest: /var/www/html/default/
  notify:
  - reload nginx
